/* auto-generated by NAPI-RS */
/* eslint-disable */
/* prettier-ignore */

const { existsSync, readFileSync } = require("fs");
const { join } = require("path");

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
	// For Node 10
	if (!process.report || typeof process.report.getReport !== "function") {
		try {
			const lddPath = require("child_process")
				.execSync("which ldd")
				.toString()
				.trim();
			return readFileSync(lddPath, "utf8").includes("musl");
		} catch {
			return true;
		}
	} else {
		const { glibcVersionRuntime } = process.report.getReport().header;
		return !glibcVersionRuntime;
	}
}

switch (platform) {
	case "darwin":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-darwin-x64");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-darwin-arm64");
				} else {
					throw new Error(`Unsupported architecture on macOS: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	case "linux":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else if (isMusl()) {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-linux-x64-musl");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-linux-arm64-musl");
				} else {
					throw new Error(`Unsupported architecture on Linux musl: ${arch}`);
				}
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-linux-x64-gnu");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-linux-arm64-gnu");
				} else {
					throw new Error(`Unsupported architecture on Linux: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	case "win32":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-win32-x64-msvc");
				} else {
					throw new Error(`Unsupported architecture on Windows: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	default:
		throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
	if (loadError) {
		throw loadError;
	}
	throw new Error(`Failed to load native binding`);
}

// Convert array to Float32Array if needed
function toFloat32Array(arr) {
	if (arr instanceof Float32Array) {
		return arr;
	}
	return new Float32Array(arr);
}

// Convert VectorItem to use Float32Array
function convertVectorItem(item) {
	return {
		...item,
		vector: toFloat32Array(item.vector),
	};
}

// Convert MultiVectorItem to use Float32Arrays
function convertMultiVectorItem(item) {
	return {
		...item,
		vectors: item.vectors.map(toFloat32Array),
	};
}

// Wrap VectorDatabase to handle array conversion
const NativeVectorDatabase = nativeBinding.VectorDatabase;

class VectorDatabase {
	constructor(nativeDb) {
		this._native = nativeDb;
	}

	set(items) {
		return this._native.set(items.map(convertVectorItem));
	}

	setMultiVec(items) {
		return this._native.setMultiVec(items.map(convertMultiVectorItem));
	}

	search(query, k, ef, filter, maxDistance) {
		return this._native.search(query, k, ef, filter, maxDistance);
	}

	searchMultiVec(query, k, rerank, rerankFactor) {
		return this._native.searchMultiVec(query, k, rerank, rerankFactor);
	}

	searchBatch(queries, k, ef) {
		return this._native.searchBatch(queries, k, ef);
	}

	get(id) {
		return this._native.get(id);
	}

	delete(ids) {
		return this._native.delete(ids);
	}

	deleteByFilter(filter) {
		return this._native.deleteByFilter(filter);
	}

	count(filter) {
		return this._native.count(filter);
	}

	update(id, vector, metadata) {
		return this._native.update(id, vector, metadata);
	}

	get length() {
		return this._native.length;
	}

	get dimensions() {
		return this._native.dimensions;
	}

	get isMultiVector() {
		return this._native.isMultiVector;
	}

	isEmpty() {
		return this._native.isEmpty();
	}

	stats() {
		return this._native.stats();
	}

	get efSearch() {
		return this._native.efSearch;
	}

	set efSearch(value) {
		this._native.efSearch = value;
	}

	collection(name) {
		return new VectorDatabase(this._native.collection(name));
	}

	collections() {
		return this._native.collections();
	}

	deleteCollection(name) {
		return this._native.deleteCollection(name);
	}

	enableTextSearch() {
		return this._native.enableTextSearch();
	}

	get hasTextSearch() {
		return this._native.hasTextSearch;
	}

	setWithText(items) {
		return this._native.setWithText(items.map(convertVectorItem));
	}

	textSearch(query, k) {
		return this._native.textSearch(query, k);
	}

	hybridSearch(queryVector, queryText, k, filter, alpha, rrfK, subscores) {
		return this._native.hybridSearch(
			queryVector,
			queryText,
			k,
			filter,
			alpha,
			rrfK,
			subscores,
		);
	}

	flush() {
		return this._native.flush();
	}

	close() {
		return this._native.close();
	}

	optimize() {
		return this._native.optimize();
	}

	mergeFrom(other) {
		return this._native.mergeFrom(other._native);
	}

	ids() {
		return this._native.ids();
	}

	items() {
		return this._native.items();
	}

	exists(id) {
		return this._native.exists(id);
	}

	getBatch(ids) {
		return this._native.getBatch(ids);
	}
}

function open(path, options) {
	return new VectorDatabase(nativeBinding.open(path, options));
}

module.exports.VectorDatabase = VectorDatabase;
module.exports.open = open;
