/* auto-generated by NAPI-RS */
/* eslint-disable */
/* prettier-ignore */

const { existsSync, readFileSync } = require("fs");
const { join } = require("path");

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
	// For Node 10
	if (!process.report || typeof process.report.getReport !== "function") {
		try {
			const lddPath = require("child_process")
				.execSync("which ldd")
				.toString()
				.trim();
			return readFileSync(lddPath, "utf8").includes("musl");
		} catch {
			return true;
		}
	} else {
		const { glibcVersionRuntime } = process.report.getReport().header;
		return !glibcVersionRuntime;
	}
}

switch (platform) {
	case "darwin":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-darwin-x64");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-darwin-arm64");
				} else {
					throw new Error(`Unsupported architecture on macOS: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	case "linux":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else if (isMusl()) {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-linux-x64-musl");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-linux-arm64-musl");
				} else {
					throw new Error(`Unsupported architecture on Linux musl: ${arch}`);
				}
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-linux-x64-gnu");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-linux-arm64-gnu");
				} else {
					throw new Error(`Unsupported architecture on Linux: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	case "win32":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-win32-x64-msvc");
				} else {
					throw new Error(`Unsupported architecture on Windows: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	default:
		throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
	if (loadError) {
		throw loadError;
	}
	throw new Error(`Failed to load native binding`);
}

// Convert array to Float32Array if needed
function toFloat32Array(arr) {
	if (arr instanceof Float32Array) {
		return arr;
	}
	return new Float32Array(arr);
}

// Convert VectorItem to use Float32Array
function convertVectorItem(item) {
	// Items with document field are handled by native embedding
	if (item.document !== undefined && item.document !== null) {
		return item;
	}
	if (item.vector === undefined || item.vector === null) {
		if (Array.isArray(item.vectors)) {
			throw new Error(
				`Item '${item.id}' has 'vectors' field but store is single-vector. Use multiVector: true when opening the database.`,
			);
		}
		throw new Error(`Item '${item.id}' missing required 'vector' field`);
	}
	return {
		...item,
		vector: toFloat32Array(item.vector),
	};
}

// Convert MultiVectorItem to use Float32Arrays
function convertMultiVectorItem(item) {
	if (!Array.isArray(item.vectors)) {
		if (item.vector !== undefined) {
			throw new Error(
				`Item '${item.id}' has 'vector' field but store is multi-vector. Use 'vectors' field (array of vectors) instead.`,
			);
		}
		throw new Error(`Item '${item.id}' missing required 'vectors' field`);
	}
	return {
		...item,
		vectors: item.vectors.map(toFloat32Array),
	};
}

// Wrap VectorDatabase to handle array conversion
const NativeVectorDatabase = nativeBinding.VectorDatabase;

class VectorDatabase {
	constructor(nativeDb) {
		this._native = nativeDb;
	}

	/**
	 * Insert or update vectors.
	 *
	 * Works for both single-vector and multi-vector stores:
	 * - Single-vector: items have `vector` field
	 * - Multi-vector: items have `vectors` field (array of vectors)
	 *
	 * When any item includes a `text` field, text search is automatically enabled.
	 *
	 * @param {Array<{id: string, vector?: Float32Array|number[], vectors?: Float32Array[]|number[][], metadata?: object, text?: string}>} items
	 * @returns {number} Number of vectors inserted/updated
	 */
	set(items) {
		if (!Array.isArray(items)) {
			throw new Error("set() requires an array of items");
		}
		if (items.length === 0) {
			return 0;
		}
		// Unified set() handles both single and multi-vector via native set()
		return this._native.set(items.map(this._native.isMultiVector ? convertMultiVectorItem : convertVectorItem));
	}

	/**
	 * Search for k nearest neighbors.
	 *
	 * Works for both single-vector and multi-vector stores:
	 * - Single-vector: query is number[] or Float32Array
	 * - Multi-vector: query is number[][] or Float32Array[]
	 *
	 * @param {number[]|Float32Array|number[][]|Float32Array[]} query - Query vector(s)
	 * @param {number} k - Number of results to return
	 * @param {object} [options] - Search options: {filter?, ef?, maxDistance?}
	 * @returns {Array<{id: string, distance: number, score: number, metadata: object}>}
	 */
	search(query, k, options) {
		if (this._native.isMultiVector) {
			// Multi-vector store
			const rerank = options?.rerank;
			const rerankFactor = options?.rerankFactor;
			return this._native.searchMulti(query, k, rerank, rerankFactor);
		} else {
			// Single-vector store - pass options object directly to native
			return this._native.search(query, k, options);
		}
	}

	searchBatch(queries, k, ef) {
		return this._native.searchBatch(queries, k, ef);
	}

	get(id) {
		return this._native.get(id);
	}

	delete(ids) {
		return this._native.delete(ids);
	}

	deleteByFilter(filter) {
		return this._native.deleteByFilter(filter);
	}

	count(filter) {
		return this._native.count(filter);
	}

	/**
	 * Update a vector's data, metadata, and/or text.
	 *
	 * @param {string} id - Vector ID to update
	 * @param {object} options - Update options: {vector?, metadata?, text?}
	 */
	update(id, options) {
		return this._native.update(id, options);
	}

	get length() {
		return this._native.length;
	}

	get dimensions() {
		return this._native.dimensions;
	}

	get isMultiVector() {
		return this._native.isMultiVector;
	}

	get hasEmbeddingFn() {
		return this._native.hasEmbeddingFn;
	}

	isEmpty() {
		return this._native.isEmpty();
	}

	stats() {
		return this._native.stats();
	}

	get efSearch() {
		return this._native.efSearch;
	}

	set efSearch(value) {
		this._native.efSearch = value;
	}

	collection(name, embeddingFn) {
		return new VectorDatabase(this._native.collection(name, embeddingFn));
	}

	collections() {
		return this._native.collections();
	}

	deleteCollection(name) {
		return this._native.deleteCollection(name);
	}

	get hasTextSearch() {
		return this._native.hasTextSearch;
	}

	/**
	 * Search using text only (BM25 scoring).
	 *
	 * @param {string} query - Text query
	 * @param {number} k - Number of results
	 * @returns {Array<{id: string, score: number, metadata: object}>}
	 */
	searchText(query, k) {
		return this._native.searchText(query, k);
	}

	/**
	 * Hybrid search combining vector similarity and text relevance.
	 *
	 * @param {number[]|Float32Array} queryVector - Query embedding
	 * @param {string} queryText - Text query for BM25
	 * @param {number} k - Number of results
	 * @param {object} [options] - Options: {filter?, alpha?, rrfK?, subscores?}
	 * @returns {Array<{id: string, score: number, metadata: object, keywordScore?: number, semanticScore?: number}>}
	 */
	searchHybrid(queryVector, queryText, k, options) {
		return this._native.searchHybrid(queryVector, queryText, k, options);
	}

	flush() {
		return this._native.flush();
	}

	close() {
		return this._native.close();
	}

	optimize() {
		return this._native.optimize();
	}

	mergeFrom(other, keyPrefix) {
		return this._native.mergeFrom(other._native, keyPrefix);
	}

	info() {
		return this._native.info();
	}

	ids() {
		return this._native.ids();
	}

	items() {
		return this._native.items();
	}

	exists(id) {
		return this._native.exists(id);
	}

	getBatch(ids) {
		return this._native.getBatch(ids);
	}

	compact() {
		return this._native.compact();
	}

	enableSparse() {
		return this._native.enableSparse();
	}

	get hasSparse() {
		return this._native.hasSparse;
	}

	setSparse(id, sparse, metadata) {
		return this._native.setSparse(id, sparse, metadata);
	}

	setHybridSparse(id, vector, sparse, metadata) {
		return this._native.setHybridSparse(id, vector, sparse, metadata);
	}

	sparseSearch(query, k, options) {
		return this._native.sparseSearch(query, k, options);
	}

	hybridSparseSearch(queryVector, sparseQuery, k, options) {
		return this._native.hybridSparseSearch(queryVector, sparseQuery, k, options);
	}

	// --- Edge graph API ---

	addEdge(fromId, toId, edgeType, weight, metadata) {
		return this._native.addEdge(fromId, toId, edgeType, weight, metadata);
	}

	removeEdge(fromId, toId, edgeType) {
		return this._native.removeEdge(fromId, toId, edgeType);
	}

	getEdges(id, direction, edgeType) {
		return this._native.getEdges(id, direction, edgeType);
	}

	traverse(startId, direction, maxDepth, edgeType) {
		return this._native.traverse(startId, direction, maxDepth, edgeType);
	}

	expand(ids, direction, edgeType) {
		return this._native.expand(ids, direction, edgeType);
	}

	get edgeCount() {
		return this._native.edgeCount;
	}
}

function open(path, options, embeddingFn) {
	return new VectorDatabase(nativeBinding.open(path, options, embeddingFn));
}

module.exports.VectorDatabase = VectorDatabase;
module.exports.open = open;
