/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class VectorDatabase {
	/**
	 * Insert or update vectors.
	 *
	 * Accepts an array of items with id, vector, and optional metadata.
	 */
	set(items: Array<VectorItem>): Array<number>;
	/**
	 * Search for k nearest neighbors.
	 *
	 * @param query - Query vector (number[] or Float32Array)
	 * @param k - Number of results to return
	 * @param ef - Optional search width override
	 * @returns Array of {id, distance, metadata}
	 */
	search(
		query: Array<number> | Float32Array,
		k: number,
		ef?: number | undefined | null,
	): Array<SearchResult>;
	/**
	 * Batch search with parallel execution (async).
	 *
	 * Runs searches in parallel using rayon, returns Promise.
	 */
	searchBatch(
		queries: Array<Array<number> | Float32Array>,
		k: number,
		ef?: number | undefined | null,
	): Promise<Array<Array<SearchResult>>>;
	/** Get a vector by ID. */
	get(id: string): GetResult | null;
	/**
	 * Delete vectors by ID.
	 *
	 * @returns Number of vectors deleted
	 */
	delete(ids: Array<string>): number;
	/** Update a vector's data and/or metadata. */
	update(
		id: string,
		vector: Array<number> | Float32Array,
		metadata?: Record<string, unknown> | undefined,
	): void;
	/** Save database to disk. */
	save(): void;
	/** Get number of vectors in database. */
	get count(): number;
	/** Get current ef_search value. */
	get efSearch(): number | null;
	/** Set ef_search value. */
	set efSearch(efSearch: number);
	/** Get or create a named collection. */
	collection(name: string): VectorDatabase;
	/** List all collections. */
	collections(): Array<string>;
	/** Delete a collection. */
	deleteCollection(name: string): void;
	/** Merge another database into this one. */
	mergeFrom(other: VectorDatabase): number;
}

export interface GetResult {
	id: string;
	vector: Array<number>;
	metadata: Record<string, unknown>;
}

/**
 * Open or create a vector database.
 *
 * @param path - Database directory path (use ":memory:" for in-memory)
 * @param options - Optional configuration
 * @returns VectorDatabase instance
 */
export declare function open(
	path: string,
	options?: OpenOptions | undefined | null,
): VectorDatabase;

export interface OpenOptions {
	dimensions?: number;
	m?: number;
	efConstruction?: number;
}

export interface SearchResult {
	id: string;
	distance: number;
	/** Metadata as JSON (using serde-json feature) */
	metadata: Record<string, unknown>;
}

export interface VectorItem {
	id: string;
	/** Vector data as array of numbers */
	vector: Array<number>;
	/** Optional metadata */
	metadata?: Record<string, unknown> | undefined;
	/** Optional document text (stored in metadata.document) */
	document?: string;
}
