/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class VectorDatabase {
  /**
   * Insert or update vectors.
   *
   * Works for both single-vector and multi-vector stores:
   * - Single-vector: items have `vector` field
   * - Multi-vector: items have `vectors` field (array of vectors)
   *
   * @param items - Array of {id, vector, metadata?} or {id, vectors, metadata?}
   * @returns Array of internal indices
   */
  set(items: Array<SetItem>): Array<number>
  /**
   * Insert or update multi-vector documents.
   *
   * @deprecated Use set() with vectors field instead
   *
   * For multi-vector stores (ColBERT-style). Each document has multiple token vectors.
   *
   * @param items - Array of {id, vectors: Float32Array[], metadata?}
   * @returns Array of internal indices
   */
  setMultiVec(items: Array<MultiVectorItem>): Array<number>
  /**
   * Search multi-vector store with optional reranking.
   *
   * @deprecated Use search() with options instead
   *
   * For multi-vector stores (ColBERT-style). Query is multiple token vectors.
   *
   * @param query - Query tokens (number[][] or Float32Array[])
   * @param k - Number of results to return
   * @param rerank - Enable MaxSim reranking for better quality (default: true)
   * @param rerankFactor - Fetch k*rerankFactor candidates before reranking (default: 4)
   * @returns Array of {id, distance, metadata}
   */
  searchMultiVec(query: Array<Array<number>> | Array<Float32Array>, k: number, rerank?: boolean | undefined | null, rerankFactor?: number | undefined | null): Array<SearchResult>
  /**
   * Search for k nearest neighbors.
   *
   * @param query - Query vector (number[] or Float32Array)
   * @param k - Number of results to return
   * @param ef - Optional search width override
   * @param filter - Optional metadata filter (e.g., {category: "foo"} or {price: {$gt: 10}})
   * @param maxDistance - Optional max distance threshold (filter out distant results)
   * @returns Array of {id, distance, metadata}
   */
  search(query: Array<number> | Float32Array, k: number, ef?: number | undefined | null, filter?: Record<string, unknown> | undefined, maxDistance?: number | undefined | null): Array<SearchResult>
  /**
   * Batch search with parallel execution (async).
   *
   * Runs searches in parallel using rayon on a blocking thread pool,
   * keeping the Node.js event loop free.
   */
  searchBatch(queries: Array<Array<number> | Float32Array>, k: number, ef?: number | undefined | null): Promise<Array<Array<SearchResult>>>
  /** Get a vector by ID. */
  get(id: string): GetResult | null
  /**
   * Delete vectors by ID.
   *
   * @returns Number of vectors deleted
   */
  delete(ids: Array<string>): number
  /**
   * Delete vectors matching a metadata filter.
   *
   * Evaluates the filter against all vectors and deletes those that match.
   * Uses the same MongoDB-style filter syntax as search().
   *
   * @param filter - MongoDB-style metadata filter
   * @returns Number of vectors deleted
   *
   * @example
   * ```javascript
   * // Delete by equality
   * db.deleteByFilter({ status: "archived" });
   *
   * // Delete with comparison
   * db.deleteByFilter({ score: { $lt: 0.5 } });
   *
   * // Complex filter
   * db.deleteByFilter({ $and: [{ type: "draft" }, { age: { $gt: 30 } }] });
   * ```
   */
  deleteByFilter(filter: Record<string, unknown>): number
  /**
   * Count vectors, optionally filtered by metadata.
   *
   * Without a filter, returns total count (same as db.length).
   * With a filter, returns count of vectors matching the filter.
   *
   * @param filter - Optional MongoDB-style metadata filter
   * @returns Number of vectors (matching filter if provided)
   *
   * @example
   * ```javascript
   * // Total count
   * const total = db.count();
   *
   * // Filtered count
   * const active = db.count({ status: "active" });
   *
   * // With comparison operators
   * const highScore = db.count({ score: { $gte: 0.8 } });
   * ```
   */
  count(filter?: Record<string, unknown> | undefined): number
  /** Update a vector's data and/or metadata. */
  update(id: string, vector: Array<number> | Float32Array, metadata?: Record<string, unknown> | undefined): void
  /** Get number of vectors in database. */
  get length(): number
  /** Get vector dimensions of this database. */
  get dimensions(): number
  /** Check if this is a multi-vector store. */
  get isMultiVector(): boolean
  /** Check if database is empty. */
  isEmpty(): boolean
  /** Get database statistics. */
  stats(): StatsResult
  /** Get current ef_search value. */
  get efSearch(): number
  /** Set ef_search value. */
  set efSearch(efSearch: number)
  /**
   * Get or create a named collection.
   *
   * Collection handles share state - changes made through one handle
   * are immediately visible through another (no flush required).
   */
  collection(name: string): VectorDatabase
  /** List all collections. */
  collections(): Array<string>
  /** Delete a collection. */
  deleteCollection(name: string): void
  /**
   * Enable text search for hybrid (vector + text) search.
   *
   * Must be called before using setWithText() or hybridSearch().
   */
  enableTextSearch(): void
  /** Check if text search is enabled. */
  get hasTextSearch(): boolean
  /**
   * Set vectors with associated text for hybrid search.
   *
   * @param items - Array of {id, vector, text, metadata?}
   * @returns Array of internal indices
   */
  setWithText(items: Array<VectorItemWithText>): Array<number>
  /**
   * Search using text only (BM25 scoring).
   *
   * @param query - Text query
   * @param k - Number of results
   * @returns Array of {id, score, metadata}
   */
  textSearch(query: string, k: number): Array<TextSearchResult>
  /**
   * Hybrid search combining vector similarity and text relevance.
   *
   * Uses Reciprocal Rank Fusion (RRF) to combine HNSW and BM25 results.
   *
   * @param queryVector - Query embedding
   * @param queryText - Text query for BM25
   * @param k - Number of results
   * @param filter - Optional metadata filter
   * @param alpha - Weight for vector vs text (0.0=text only, 1.0=vector only, default=0.5)
   * @param rrfK - RRF constant (default=60, higher reduces rank influence)
   * @param subscores - Return separate keyword_score and semantic_score (default: false)
   * @returns Array of {id, score, metadata, keyword_score?, semantic_score?}
   */
  hybridSearch(queryVector: Array<number> | Float32Array, queryText: string, k: number, filter?: Record<string, unknown> | undefined, alpha?: number | undefined | null, rrfK?: number | undefined | null, subscores?: boolean | undefined | null): Array<HybridSearchResult>
  /**
   * Flush pending changes to disk.
   *
   * For hybrid search, this commits text index changes.
   */
  flush(): void
  /**
   * Compact the database by removing deleted records and reclaiming space.
   *
   * This operation removes tombstoned records, reassigns indices to be
   * contiguous, and rebuilds the search index. Call after bulk deletes
   * to reclaim memory and improve search performance.
   *
   * @returns Number of deleted records that were removed
   *
   * @example
   * ```typescript
   * // After bulk delete
   * db.delete(staleIds);
   * const removed = db.compact();
   * console.log(`Removed ${removed} deleted records`);
   * ```
   */
  compact(): number
  /**
   * Close the database and release file locks.
   *
   * After calling close(), the database is no longer usable.
   * Any subsequent operations will fail or return empty results.
   *
   * This is useful when you need to reopen the same database path
   * in the same process, since JavaScript doesn't have deterministic
   * object destruction like Python's `del`.
   */
  close(): void
  /**
   * Optimize index for cache-efficient search.
   *
   * Reorders nodes for better memory locality, improving search performance by 6-40%.
   * Call after inserting a large batch of vectors.
   *
   * @returns Number of nodes reordered
   */
  optimize(): number
  /** Merge another database into this one. */
  mergeFrom(other: VectorDatabase): number
  /**
   * List all vector IDs (without loading vector data).
   *
   * Efficient way to get all IDs for iteration, export, or debugging.
   * @returns Array of all vector IDs in the database
   */
  ids(): Array<string>
  /**
   * Get all items as array of {id, vector, metadata}.
   *
   * Returns all vectors with their IDs and metadata.
   * For large datasets, consider using ids() and get() in batches.
   */
  items(): Array<GetResult>
  /**
   * Check if an ID exists in the database.
   *
   * @param id - Vector ID to check
   * @returns true if ID exists and is not deleted
   */
  exists(id: string): boolean
  /**
   * Get multiple vectors by ID.
   *
   * Batch version of get(). More efficient than calling get() in a loop.
   *
   * @param ids - Array of vector IDs to retrieve
   * @returns Array of results in same order as input, null for missing IDs
   */
  getBatch(ids: Array<string>): Array<GetResult | undefined | null>
}

export interface GetResult {
  id: string
  vector: Float32Array
  metadata: Record<string, unknown>
}

export interface HybridSearchResult {
  id: string
  score: number
  metadata: Record<string, unknown>
  /** BM25 keyword matching score (null if document only matched vector search) */
  keywordScore?: number
  /** Vector similarity score (null if document only matched text search) */
  semanticScore?: number
}

export interface MultiVectorItem {
  id: string
  /** Multi-vector data as array of Float32Arrays */
  vectors: Float32Array[]
  /** Optional metadata */
  metadata?: Record<string, unknown> | undefined
}

/**
 * Open or create a vector database.
 *
 * @param path - Database directory path (use ":memory:" for in-memory)
 * @param options - Optional configuration (see OpenOptions for defaults)
 * @returns VectorDatabase instance
 *
 * @example
 * ```javascript
 * // Simple usage with defaults
 * const db = omendb.open("./mydb");
 *
 * // With custom HNSW parameters
 * const db = omendb.open("./mydb", {
 *   dimensions: 384,
 *   m: 32,
 *   efConstruction: 200,
 *   efSearch: 150
 * });
 *
 * // With SQ8 quantization (4x memory reduction, ~99% recall)
 * const db = omendb.open("./mydb", {
 *   dimensions: 128,
 *   quantization: true  // or "sq8"
 * });
 *
 * // Quantization with custom rescore settings
 * const db = omendb.open("./mydb", {
 *   dimensions: 128,
 *   quantization: true,
 *   rescore: false,    // Disable rescore for max speed
 *   oversample: 5.0    // Or increase oversample for better recall
 * });
 * ```
 */
export declare function open(path: string, options?: OpenOptions | undefined | null): VectorDatabase

/**
 * Configuration options for opening a vector database.
 *
 * All fields are optional with sensible defaults:
 * - dimensions: 128 (auto-detected on first insert if not specified)
 * - m: 16 (HNSW neighbors per node, higher = better recall, more memory)
 * - efConstruction: 100 (build quality, higher = better graph, slower build)
 * - efSearch: 100 (search quality, higher = better recall, slower search)
 * - quantization: null (true/"sq8" for 4x compression, ~99% recall)
 * - rescore: true when quantization enabled (rerank candidates with exact distance)
 * - oversample: 3.0 (fetch k*oversample candidates when rescoring)
 * - metric: "l2" (distance metric: "l2", "euclidean", "cosine", "dot", "ip")
 */
export interface OpenOptions {
  /** Vector dimensions (default: 128, auto-detected on first insert) */
  dimensions?: number
  /** HNSW M parameter: neighbors per node (default: 16, range: 4-64) */
  m?: number
  /** HNSW ef_construction: build quality (default: 100, must be >= m) */
  efConstruction?: number
  /** HNSW ef_search: search quality/speed tradeoff (default: 100) */
  efSearch?: number
  /**
   * Quantization mode (default: null = no quantization)
   * - true or "sq8": SQ8 4x compression, ~99% recall (RECOMMENDED)
   * - false/null: Full precision (no quantization)
   */
  quantization?: boolean | string | number | null | undefined
  /**
   * Rescore candidates with exact distance (default: true when quantization enabled)
   * Set to false for maximum speed at the cost of ~20% recall
   */
  rescore?: boolean
  /**
   * Oversampling factor for rescoring (default: 3.0)
   * Fetches k*oversample candidates then reranks to return top k
   */
  oversample?: number
  /** Distance metric: "l2"/"euclidean" (default), "cosine", "dot"/"ip" */
  metric?: string
  /**
   * Enable multi-vector mode for ColBERT-style retrieval
   * - true: Enable with default config (repetitions=5, partition_bits=3)
   * - { repetitions?, partitionBits?, seed? }: Custom config
   * - false/null: Disabled (default, single-vector mode)
   */
  multiVector?: boolean | { repetitions?: number; partitionBits?: number; seed?: number } | null | undefined
}

export interface SearchResult {
  id: string
  distance: number
  /** Metadata as JSON (using serde-json feature) */
  metadata: Record<string, unknown>
}

export interface SetItem {
  id: string
  /** Single vector data (for regular stores) */
  vector?: Float32Array
  /** Multi-vector data (for multi-vector stores) */
  vectors?: Float32Array[] | undefined
  /** Optional metadata */
  metadata?: Record<string, unknown> | undefined
  /** Optional document text (stored in metadata.document) */
  document?: string
}

export interface StatsResult {
  dimensions: number
  count: number
  path: string
}

export interface TextSearchResult {
  id: string
  score: number
  metadata: Record<string, unknown>
}

export interface VectorItem {
  id: string
  /** Vector data as Float32Array */
  vector: Float32Array
  /** Optional metadata */
  metadata?: Record<string, unknown> | undefined
  /** Optional document text (stored in metadata.document) */
  document?: string
}

export interface VectorItemWithText {
  id: string
  vector: Float32Array
  text: string
  metadata?: Record<string, unknown> | undefined
}
