/* auto-generated by NAPI-RS */
/* eslint-disable */
/* prettier-ignore */

const { existsSync, readFileSync } = require("fs");
const { join } = require("path");

const { platform, arch } = process;

let nativeBinding = null;
let localFileExisted = false;
let loadError = null;

function isMusl() {
	// For Node 10
	if (!process.report || typeof process.report.getReport !== "function") {
		try {
			const lddPath = require("child_process")
				.execSync("which ldd")
				.toString()
				.trim();
			return readFileSync(lddPath, "utf8").includes("musl");
		} catch {
			return true;
		}
	} else {
		const { glibcVersionRuntime } = process.report.getReport().header;
		return !glibcVersionRuntime;
	}
}

switch (platform) {
	case "darwin":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-darwin-x64");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-darwin-arm64");
				} else {
					throw new Error(`Unsupported architecture on macOS: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	case "linux":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else if (isMusl()) {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-linux-x64-musl");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-linux-arm64-musl");
				} else {
					throw new Error(`Unsupported architecture on Linux musl: ${arch}`);
				}
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-linux-x64-gnu");
				} else if (arch === "arm64") {
					nativeBinding = require("@omendb/omendb-linux-arm64-gnu");
				} else {
					throw new Error(`Unsupported architecture on Linux: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	case "win32":
		localFileExisted = existsSync(join(__dirname, "omendb.node"));
		try {
			if (localFileExisted) {
				nativeBinding = require("./omendb.node");
			} else {
				if (arch === "x64") {
					nativeBinding = require("@omendb/omendb-win32-x64-msvc");
				} else {
					throw new Error(`Unsupported architecture on Windows: ${arch}`);
				}
			}
		} catch (e) {
			loadError = e;
		}
		break;
	default:
		throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`);
}

if (!nativeBinding) {
	if (loadError) {
		throw loadError;
	}
	throw new Error(`Failed to load native binding`);
}

const { VectorDatabase, open } = nativeBinding;

module.exports.VectorDatabase = VectorDatabase;
module.exports.open = open;
